FROM openeuler/openeuler:23.03 as BUILDER
RUN yum update -y && yum install golang -y  && go env -w GOPROXY=https://goproxy.cn,direct
RUN mkdir -p /go/src/gitee.com/openeuler/k8s_exporter
COPY . /go/src/gitee.com/openeuler/k8s_exporter
RUN cd /go/src/gitee.com/openeuler/k8s_exporter && go mod tidy && CGO_ENABLED=0 go build -v -o ./k8s_exporter main.go

FROM openeuler/openeuler:22.03
RUN mkdir -p /opt/app/conf/
RUN mkdir -p /opt/app/logs/
RUN touch /opt/app/logs/k8s_exporter.log
COPY ./conf/app.conf /opt/app/conf/app.conf
COPY --from=BUILDER /go/src/gitee.com/openeuler/k8s_exporter/k8s_exporter /opt/app
WORKDIR /opt/app/
ENTRYPOINT ["/opt/app/k8s_exporter"]
EXPOSE 9201